//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpineViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpineViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于 .
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atlas文件不存在.
        /// </summary>
        internal static string atlasNotExist {
            get {
                return ResourceManager.GetString("atlasNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string categoryCustom {
            get {
                return ResourceManager.GetString("categoryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0] 导出.
        /// </summary>
        internal static string categoryExport {
            get {
                return ResourceManager.GetString("categoryExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] 预览.
        /// </summary>
        internal static string categoryPreview {
            get {
                return ResourceManager.GetString("categoryPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  项，共 .
        /// </summary>
        internal static string countInfoStatusMidfix {
            get {
                return ResourceManager.GetString("countInfoStatusMidfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择 .
        /// </summary>
        internal static string countInfoStatusPrefix {
            get {
                return ResourceManager.GetString("countInfoStatusPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  项.
        /// </summary>
        internal static string countInfoStatusSuffix {
            get {
                return ResourceManager.GetString("countInfoStatusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相关联的 SpineListView.
        /// </summary>
        internal static string descAssociatedSpineListView {
            get {
                return ResourceManager.GetString("descAssociatedSpineListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用于显示画面属性的属性页.
        /// </summary>
        internal static string descDisplayImageProperties {
            get {
                return ResourceManager.GetString("descDisplayImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用于显示模型属性的组合属性页.
        /// </summary>
        internal static string descModelAttributes {
            get {
                return ResourceManager.GetString("descModelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色.
        /// </summary>
        internal static string displayBackgroundColor {
            get {
                return ResourceManager.GetString("displayBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画面中心点.
        /// </summary>
        internal static string displayCenter {
            get {
                return ResourceManager.GetString("displayCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平翻转.
        /// </summary>
        internal static string displayFlipHorizontal {
            get {
                return ResourceManager.GetString("displayFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直翻转.
        /// </summary>
        internal static string displayFlipVertical {
            get {
                return ResourceManager.GetString("displayFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大帧率.
        /// </summary>
        internal static string displayMaximumFrameRate {
            get {
                return ResourceManager.GetString("displayMaximumFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅渲染选中.
        /// </summary>
        internal static string displayRenderSelected {
            get {
                return ResourceManager.GetString("displayRenderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分辨率.
        /// </summary>
        internal static string displayResolution {
            get {
                return ResourceManager.GetString("displayResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转.
        /// </summary>
        internal static string displayRotation {
            get {
                return ResourceManager.GetString("displayRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示坐标轴.
        /// </summary>
        internal static string displayShowAxis {
            get {
                return ResourceManager.GetString("displayShowAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放.
        /// </summary>
        internal static string displayZoom {
            get {
                return ResourceManager.GetString("displayZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨骼加载失败.
        /// </summary>
        internal static string errorLoadSkeleton {
            get {
                return ResourceManager.GetString("errorLoadSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择 .
        /// </summary>
        internal static string itemCountPrefix {
            get {
                return ResourceManager.GetString("itemCountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  个文件.
        /// </summary>
        internal static string itemCountSuffix {
            get {
                return ResourceManager.GetString("itemCountSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共发现 .
        /// </summary>
        internal static string loadAllSkeletonPrefix {
            get {
                return ResourceManager.GetString("loadAllSkeletonPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  个可加载骨骼，数量较多，是否一次性全部加载？.
        /// </summary>
        internal static string loadAllSkeletonSuffix {
            get {
                return ResourceManager.GetString("loadAllSkeletonSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误信息.
        /// </summary>
        internal static string msgBoxError {
            get {
                return ResourceManager.GetString("msgBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示信息.
        /// </summary>
        internal static string msgBoxInfo {
            get {
                return ResourceManager.GetString("msgBoxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作确认.
        /// </summary>
        internal static string msgBoxQuest {
            get {
                return ResourceManager.GetString("msgBoxQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告信息.
        /// </summary>
        internal static string msgBoxWarning {
            get {
                return ResourceManager.GetString("msgBoxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接已复制到剪贴板，请前往浏览器进行访问.
        /// </summary>
        internal static string notifyCopyGithubLink {
            get {
                return ResourceManager.GetString("notifyCopyGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数错误.
        /// </summary>
        internal static string parameterError {
            get {
                return ResourceManager.GetString("parameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已处理 .
        /// </summary>
        internal static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认移除所有 .
        /// </summary>
        internal static string removeAllItemPrefix {
            get {
                return ResourceManager.GetString("removeAllItemPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定移除所选 .
        /// </summary>
        internal static string removeItemConfirmPrefix {
            get {
                return ResourceManager.GetString("removeItemConfirmPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  项吗？.
        /// </summary>
        internal static string removeItemConfirmSuffix {
            get {
                return ResourceManager.GetString("removeItemConfirmSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言已设为英语。立即重启应用程序吗？.
        /// </summary>
        internal static string restartPrompt {
            get {
                return ResourceManager.GetString("restartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要重新启动应用程序!.
        /// </summary>
        internal static string restartTitle {
            get {
                return ResourceManager.GetString("restartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skel文件不存在.
        /// </summary>
        internal static string skelNotExist {
            get {
                return ResourceManager.GetString("skelNotExist", resourceCulture);
            }
        }
    }
}
