//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpineViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpineViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于 .
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动画.
        /// </summary>
        internal static string animation {
            get {
                return ResourceManager.GetString("animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atlas文件不存在.
        /// </summary>
        internal static string atlasNotExist {
            get {
                return ResourceManager.GetString("atlasNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to atlas文件路径.
        /// </summary>
        internal static string atlasPath {
            get {
                return ResourceManager.GetString("atlasPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本信息.
        /// </summary>
        internal static string basicInfo {
            get {
                return ResourceManager.GetString("basicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义.
        /// </summary>
        internal static string categoryCustom {
            get {
                return ResourceManager.GetString("categoryCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0] 导出.
        /// </summary>
        internal static string categoryExport {
            get {
                return ResourceManager.GetString("categoryExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] FFmpeg 基本参数.
        /// </summary>
        internal static string categoryFFmpegParameter {
            get {
                return ResourceManager.GetString("categoryFFmpegParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [3] 格式参数.
        /// </summary>
        internal static string categoryFormatParameters {
            get {
                return ResourceManager.GetString("categoryFormatParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2] 帧序列参数.
        /// </summary>
        internal static string categoryFrameSequenceParameters {
            get {
                return ResourceManager.GetString("categoryFrameSequenceParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] 预览.
        /// </summary>
        internal static string categoryPreview {
            get {
                return ResourceManager.GetString("categoryPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] 单帧画面.
        /// </summary>
        internal static string categorySingleFrame {
            get {
                return ResourceManager.GetString("categorySingleFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] 视频参数.
        /// </summary>
        internal static string categoryVideoParameters {
            get {
                return ResourceManager.GetString("categoryVideoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  项，共 .
        /// </summary>
        internal static string countInfoStatusMidfix {
            get {
                return ResourceManager.GetString("countInfoStatusMidfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择 .
        /// </summary>
        internal static string countInfoStatusPrefix {
            get {
                return ResourceManager.GetString("countInfoStatusPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  项.
        /// </summary>
        internal static string countInfoStatusSuffix {
            get {
                return ResourceManager.GetString("countInfoStatusSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调试.
        /// </summary>
        internal static string debug {
            get {
                return ResourceManager.GetString("debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用预览画面分辨率的情况下, 允许内容溢出到边缘和填充区域.
        /// </summary>
        internal static string descAllowContentOverflow {
            get {
                return ResourceManager.GetString("descAllowContentOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小于该值的像素点会被认为是透明像素.
        /// </summary>
        internal static string descAlphaThreshold {
            get {
                return ResourceManager.GetString("descAlphaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 相关联的 SpineListView.
        /// </summary>
        internal static string descAssociatedSpineListView {
            get {
                return ResourceManager.GetString("descAssociatedSpineListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 根据导出内容自动设置分辨率, 四周填充距离和内容溢出参数将会被忽略.
        /// </summary>
        internal static string descAutoResolution {
            get {
                return ResourceManager.GetString("descAutoResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -c:v, 要使用的编码器\n建议使用硬件加速, libaom-av1 速度非常非常非常慢.
        /// </summary>
        internal static string descAvifEncoder {
            get {
                return ResourceManager.GetString("descAvifEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 要使用的背景色, 格式为 #RRGGBBAA.
        /// </summary>
        internal static string descBackgroundColor {
            get {
                return ResourceManager.GetString("descBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -crf, 取值范围 0-63, 建议范围 18-28, 默认取值 23, 数值越小则输出质量越高.
        /// </summary>
        internal static string descCRF {
            get {
                return ResourceManager.GetString("descCRF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 使用 \&quot;ffmpeg -h encoder=&lt;编码器&gt;\&quot; 查看编码器支持的参数\n使用 \&quot;ffmpeg -h muxer=&lt;文件格式&gt;\&quot; 查看文件格式支持的参数.
        /// </summary>
        internal static string descCustomArgument {
            get {
                return ResourceManager.GetString("descCustomArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用于显示画面属性的属性页.
        /// </summary>
        internal static string descDisplayImageProperties {
            get {
                return ResourceManager.GetString("descDisplayImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出图像的每英寸像素数，用于调整图像的物理尺寸.
        /// </summary>
        internal static string descDPI {
            get {
                return ResourceManager.GetString("descDPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可以从模型列表查看动画时长, 如果小于 0, 则在逐个导出时每个模型使用各自的所有轨道动画时长最大值.
        /// </summary>
        internal static string descDuration {
            get {
                return ResourceManager.GetString("descDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否将模型在同一个画面上导出单个文件，否则逐个导出模型.
        /// </summary>
        internal static string descExportSingle {
            get {
                return ResourceManager.GetString("descExportSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -f, 文件格式.
        /// </summary>
        internal static string descFileFormat {
            get {
                return ResourceManager.GetString("descFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 与图像格式匹配的文件名后缀.
        /// </summary>
        internal static string descFileNameExtension {
            get {
                return ResourceManager.GetString("descFileNameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名后缀.
        /// </summary>
        internal static string descFilenameSuffix {
            get {
                return ResourceManager.GetString("descFilenameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 每秒画面数.
        /// </summary>
        internal static string descFPS {
            get {
                return ResourceManager.GetString("descFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧文件的后缀，同时决定帧图像格式.
        /// </summary>
        internal static string descFrameFileExtension {
            get {
                return ResourceManager.GetString("descFrameFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 当设置保留最后一帧时, 动图会更为连贯, 但是帧数可能比预期帧数多 1.
        /// </summary>
        internal static string descKeepLastFrame {
            get {
                return ResourceManager.GetString("descKeepLastFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -loop, 循环次数, 0 无限循环, 取值范围 [0, 65535].
        /// </summary>
        internal static string descLoopCount {
            get {
                return ResourceManager.GetString("descLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -lossless, 0 表示有损, 1 表示无损.
        /// </summary>
        internal static string descLoseless {
            get {
                return ResourceManager.GetString("descLoseless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画布外部的边缘距离 (Margin), 最终导出的分辨率需要加上这个边距.
        /// </summary>
        internal static string descMargin {
            get {
                return ResourceManager.GetString("descMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置调色板使用的最大颜色数量, 越多则色彩保留程度越高.
        /// </summary>
        internal static string descMaxColor {
            get {
                return ResourceManager.GetString("descMaxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用于显示模型属性的组合属性页.
        /// </summary>
        internal static string descModelAttributes {
            get {
                return ResourceManager.GetString("descModelAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逐个导出时可以留空，将逐个导出到模型自身所在目录.
        /// </summary>
        internal static string descOutputFolder {
            get {
                return ResourceManager.GetString("descOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画布内部的填充距离 (Padding), 导出的分辨率大小不会发生变化, 但是会留有四周空间.
        /// </summary>
        internal static string descPadding {
            get {
                return ResourceManager.GetString("descPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -pix_fmt, 要使用的像素格式.
        /// </summary>
        internal static string descPixelFormat {
            get {
                return ResourceManager.GetString("descPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -profile, 预设配置.
        /// </summary>
        internal static string descPreset {
            get {
                return ResourceManager.GetString("descPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览画面的视区参数，请在预览画面参数面板进行调整.
        /// </summary>
        internal static string descPreviewViewport {
            get {
                return ResourceManager.GetString("descPreviewViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -quality, 取值范围 0-100, 默认值 75.
        /// </summary>
        internal static string descQuality {
            get {
                return ResourceManager.GetString("descQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否仅导出选中的模型，请在预览画面参数面板进行调整.
        /// </summary>
        internal static string descRenderSelected {
            get {
                return ResourceManager.GetString("descRenderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否将模型在同一个画面上导出单个文件，否则逐个导出模型.
        /// </summary>
        internal static string descResolution {
            get {
                return ResourceManager.GetString("descResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许内容溢出.
        /// </summary>
        internal static string displayAllowContentOverflow {
            get {
                return ResourceManager.GetString("displayAllowContentOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 透明度阈值.
        /// </summary>
        internal static string displayAlphaThreshold {
            get {
                return ResourceManager.GetString("displayAlphaThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动分辨率.
        /// </summary>
        internal static string displayAutoResolution {
            get {
                return ResourceManager.GetString("displayAutoResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景颜色.
        /// </summary>
        internal static string displayBackgroundColor {
            get {
                return ResourceManager.GetString("displayBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 画面中心点.
        /// </summary>
        internal static string displayCenter {
            get {
                return ResourceManager.GetString("displayCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义参数.
        /// </summary>
        internal static string displayCustomArgument {
            get {
                return ResourceManager.GetString("displayCustomArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编码器.
        /// </summary>
        internal static string displayEncoder {
            get {
                return ResourceManager.GetString("displayEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出单个.
        /// </summary>
        internal static string displayExportSingle {
            get {
                return ResourceManager.GetString("displayExportSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件格式.
        /// </summary>
        internal static string displayFileFormat {
            get {
                return ResourceManager.GetString("displayFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件名后缀.
        /// </summary>
        internal static string displayFilenameSuffix {
            get {
                return ResourceManager.GetString("displayFilenameSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平翻转.
        /// </summary>
        internal static string displayFlipHorizontal {
            get {
                return ResourceManager.GetString("displayFlipHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直翻转.
        /// </summary>
        internal static string displayFlipVertical {
            get {
                return ResourceManager.GetString("displayFlipVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧率.
        /// </summary>
        internal static string displayFPS {
            get {
                return ResourceManager.GetString("displayFPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图像格式.
        /// </summary>
        internal static string displayImageFormat {
            get {
                return ResourceManager.GetString("displayImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保留最后一帧.
        /// </summary>
        internal static string displayKeepLastFrame {
            get {
                return ResourceManager.GetString("displayKeepLastFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 循环次数.
        /// </summary>
        internal static string displayLoopCount {
            get {
                return ResourceManager.GetString("displayLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无损.
        /// </summary>
        internal static string displayLoseless {
            get {
                return ResourceManager.GetString("displayLoseless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四周边缘距离.
        /// </summary>
        internal static string displayMargin {
            get {
                return ResourceManager.GetString("displayMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 调色板最大颜色数量.
        /// </summary>
        internal static string displayMaxColor {
            get {
                return ResourceManager.GetString("displayMaxColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大帧率.
        /// </summary>
        internal static string displayMaximumFrameRate {
            get {
                return ResourceManager.GetString("displayMaximumFrameRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件夹.
        /// </summary>
        internal static string displayOutputFolder {
            get {
                return ResourceManager.GetString("displayOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 四周填充距离.
        /// </summary>
        internal static string displayPadding {
            get {
                return ResourceManager.GetString("displayPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 像素格式.
        /// </summary>
        internal static string displayPixelFormat {
            get {
                return ResourceManager.GetString("displayPixelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预设.
        /// </summary>
        internal static string displayPreset {
            get {
                return ResourceManager.GetString("displayPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览画面视区.
        /// </summary>
        internal static string displayPreviewViewport {
            get {
                return ResourceManager.GetString("displayPreviewViewport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 质量.
        /// </summary>
        internal static string displayQuality {
            get {
                return ResourceManager.GetString("displayQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 仅渲染选中.
        /// </summary>
        internal static string displayRenderSelected {
            get {
                return ResourceManager.GetString("displayRenderSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分辨率.
        /// </summary>
        internal static string displayResolution {
            get {
                return ResourceManager.GetString("displayResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旋转.
        /// </summary>
        internal static string displayRotation {
            get {
                return ResourceManager.GetString("displayRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示坐标轴.
        /// </summary>
        internal static string displayShowAxis {
            get {
                return ResourceManager.GetString("displayShowAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放.
        /// </summary>
        internal static string displayZoom {
            get {
                return ResourceManager.GetString("displayZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时长.
        /// </summary>
        internal static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 骨骼加载失败.
        /// </summary>
        internal static string errorLoadSkeleton {
            get {
                return ResourceManager.GetString("errorLoadSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件版本.
        /// </summary>
        internal static string fileVersion {
            get {
                return ResourceManager.GetString("fileVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 水平翻转.
        /// </summary>
        internal static string flipX {
            get {
                return ResourceManager.GetString("flipX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 垂直翻转.
        /// </summary>
        internal static string flipY {
            get {
                return ResourceManager.GetString("flipY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹 .
        /// </summary>
        internal static string folderNotExistPrefix {
            get {
                return ResourceManager.GetString("folderNotExistPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不存在.
        /// </summary>
        internal static string folderNotExistSuffix {
            get {
                return ResourceManager.GetString("folderNotExistSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法解析颜色，请使用 #RRGGBBAA、#RRGGBB、#RGBA 或 #RGB 格式.
        /// </summary>
        internal static string formatExceptionParseColor {
            get {
                return ResourceManager.GetString("formatExceptionParseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法解析颜色，请检查格式.
        /// </summary>
        internal static string formatExceptionParseColorError {
            get {
                return ResourceManager.GetString("formatExceptionParseColorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法解析颜色，请使用已知的颜色名称.
        /// </summary>
        internal static string formatExceptionUnknownColor {
            get {
                return ResourceManager.GetString("formatExceptionUnknownColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帧.
        /// </summary>
        internal static string frame {
            get {
                return ResourceManager.GetString("frame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输出文件夹无效.
        /// </summary>
        internal static string invalidInputFolder {
            get {
                return ResourceManager.GetString("invalidInputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否隐藏.
        /// </summary>
        internal static string isHidden {
            get {
                return ResourceManager.GetString("isHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已选择 .
        /// </summary>
        internal static string itemCountPrefix {
            get {
                return ResourceManager.GetString("itemCountPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  个文件.
        /// </summary>
        internal static string itemCountSuffix {
            get {
                return ResourceManager.GetString("itemCountSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共发现 .
        /// </summary>
        internal static string loadAllSkeletonPrefix {
            get {
                return ResourceManager.GetString("loadAllSkeletonPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  个可加载骨骼，数量较多，是否一次性全部加载？.
        /// </summary>
        internal static string loadAllSkeletonSuffix {
            get {
                return ResourceManager.GetString("loadAllSkeletonSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全轨道最大时长.
        /// </summary>
        internal static string maximumTrackLength {
            get {
                return ResourceManager.GetString("maximumTrackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误信息.
        /// </summary>
        internal static string msgBoxError {
            get {
                return ResourceManager.GetString("msgBoxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示信息.
        /// </summary>
        internal static string msgBoxInfo {
            get {
                return ResourceManager.GetString("msgBoxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作确认.
        /// </summary>
        internal static string msgBoxQuest {
            get {
                return ResourceManager.GetString("msgBoxQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告信息.
        /// </summary>
        internal static string msgBoxWarning {
            get {
                return ResourceManager.GetString("msgBoxWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出单个时必须提供输出文件夹.
        /// </summary>
        internal static string mustProvideOutputFolder {
            get {
                return ResourceManager.GetString("mustProvideOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 名称.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出单个时导出时长不能为负数.
        /// </summary>
        internal static string negativeDuration {
            get {
                return ResourceManager.GetString("negativeDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 链接已复制到剪贴板，请前往浏览器进行访问.
        /// </summary>
        internal static string notifyCopyGithubLink {
            get {
                return ResourceManager.GetString("notifyCopyGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数错误.
        /// </summary>
        internal static string parameterError {
            get {
                return ResourceManager.GetString("parameterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置.
        /// </summary>
        internal static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览画面已停止渲染.
        /// </summary>
        internal static string previewRenderStopped {
            get {
                return ResourceManager.GetString("previewRenderStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已处理 .
        /// </summary>
        internal static string process {
            get {
                return ResourceManager.GetString("process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序已崩溃.
        /// </summary>
        internal static string programCrashed {
            get {
                return ResourceManager.GetString("programCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认移除所有 .
        /// </summary>
        internal static string removeAllItemPrefix {
            get {
                return ResourceManager.GetString("removeAllItemPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定移除所选 .
        /// </summary>
        internal static string removeItemConfirmPrefix {
            get {
                return ResourceManager.GetString("removeItemConfirmPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  项吗？.
        /// </summary>
        internal static string removeItemConfirmSuffix {
            get {
                return ResourceManager.GetString("removeItemConfirmSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渲染.
        /// </summary>
        internal static string render {
            get {
                return ResourceManager.GetString("render", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 资源目录.
        /// </summary>
        internal static string resourcesPath {
            get {
                return ResourceManager.GetString("resourcesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言已设为英语。立即重启应用程序吗？.
        /// </summary>
        internal static string restartPrompt {
            get {
                return ResourceManager.GetString("restartPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要重新启动应用程序!.
        /// </summary>
        internal static string restartTitle {
            get {
                return ResourceManager.GetString("restartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行出错.
        /// </summary>
        internal static string runtimeError {
            get {
                return ResourceManager.GetString("runtimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行时版本.
        /// </summary>
        internal static string runtimeVersion {
            get {
                return ResourceManager.GetString("runtimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 缩放比例.
        /// </summary>
        internal static string scale {
            get {
                return ResourceManager.GetString("scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skel文件不存在.
        /// </summary>
        internal static string skelNotExist {
            get {
                return ResourceManager.GetString("skelNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skel文件路径.
        /// </summary>
        internal static string skelPath {
            get {
                return ResourceManager.GetString("skelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 皮肤.
        /// </summary>
        internal static string skin {
            get {
                return ResourceManager.GetString("skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 插槽.
        /// </summary>
        internal static string slot {
            get {
                return ResourceManager.GetString("slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 变换.
        /// </summary>
        internal static string transform {
            get {
                return ResourceManager.GetString("transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预乘Alpha通道.
        /// </summary>
        internal static string usePremultipliedAlpha {
            get {
                return ResourceManager.GetString("usePremultipliedAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要提供有效的文件名后缀.
        /// </summary>
        internal static string validExtensionRequired {
            get {
                return ResourceManager.GetString("validExtensionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要提供有效的格式.
        /// </summary>
        internal static string validFormatRequired {
            get {
                return ResourceManager.GetString("validFormatRequired", resourceCulture);
            }
        }
    }
}
